---
branches:
  - main
  - next
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/npm"
    - npmPublish: false
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changeLogFile: docs/CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - docs/CHANGELOG.md
        - package.json
  - - "@semantic-release/github"